### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by ghost** [nnguy132/den-hoster#1]
Heya! One of my fellow discord peeps shared your program. 

I tried compiling this program for my Arduino Uno R3 atmega16u2 board and received the following error:

 [GCC]     : Compiling C file "Joystick.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega16u2 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -DARCH=ARCH_AVR8 -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/  -I. -ILUFA\LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL  -MMD -MP -MF obj/Joystick.d Joystick.c -o obj/Joystick.o

Assembler messages:
Fatal error: can't create obj/Joystick.o: No such file or directory

Any help would be appreciated :)

**Comment by nnguy132** [comment]
Hi!

Do you have the AVR toolchain and AVRdude installed?

**Comment by ghost** [comment]
Yeah, I just installed them after reading your comment. That seemed to fix my issues. Thanks! :)
