### ISSUE TITLE
problem creating the hex file

### ISSUE THREAD

**Issue by hikoae** [nnguy132/den-hoster#3]
I've received this error when i wirte command "make" for the hex file. im a very noob in arguments so thanks if u can figure me out :)

Microsoft Windows [Versione 10.0.18362.592]
(c) 2019 Microsoft Corporation. Tutti i diritti sono riservati.

C:\WINDOWS\system32>cd C:\Users\enric\Desktop\den-hoster-master

C:\Users\enric\Desktop\den-hoster-master>make
      0 [main] sh 20308 sync_with_child: child 14260(0x1EC) died before initialization with status code 0xC0000142
     71 [main] sh 20308 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
      0 [main] sh 7256 sync_with_child: child 14952(0x1EC) died before initialization with status code 0xC0000142
     63 [main] sh 7256 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
 [INFO]    : Begin compilation of project "Joystick"...

avr-gcc (WinAVR 20100110) 4.3.3
Copyright (C) 2008 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 [GCC]     : Compiling C file "Joystick.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega16u2 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -I./LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/  -MMD -MP -MF Joystick.d Joystick.c -o Joystick.o
In file included from Joystick.h:53,
                 from Joystick.c:27:
Descriptors.h:50: error: conflicting types for 'CALLBACK_USB_GetDescriptor'
./LUFA/Drivers/USB/Core/AVR8/../Device.h:133: error: previous declaration of 'CALLBACK_USB_GetDescriptor' was here
Joystick.c: In function 'SetupHardware':
Joystick.c:127: warning: implicit declaration of function 'clock_prescale_set'
Joystick.c:127: error: 'clock_div_1' undeclared (first use in this function)
Joystick.c:127: error: (Each undeclared identifier is reported only once
Joystick.c:127: error: for each function it appears in.)
make: *** [Joystick.o] Error 1

C:\Users\enric\Desktop\den-hoster-master>

**Comment by nnguy132** [comment]
If you're using winAVR I would recommend installing the avr toolchain and AVRdude and compile using GITbash

**Comment by hikoae** [comment]
thank you for the answer! ive installed avrdude and avr toolchain and gitbash, seem everything work fine (i follow this guide http://fab.cba.mit.edu/classes/863.16/doc/projects/ftsmin/windows_avr.html but i use an arduino R3 atmega16u2 maybe is different?) but when i launch make command, give me the same error:

enric@HIKOPC MINGW64 ~/desktop/den-hoster-master
$ make
 [INFO]    : Begin compilation of project \Joystick"...

avr-gcc (AVR_8_bit_GNU_Toolchain_3.6.2_1759) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 [GCC]     : Compiling C file \Joystick.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega16u2 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields -ffunction-sections -I. -I./LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_NONE -DF_USB=16000000UL -DF_CPU=16000000UL -mrelax -fno-jump-tables -x c -Os -std=gnu99 -Wstrict-prototypes -DUSE_LUFA_CONFIG_HEADER -IConfig/  -MMD -MP -MF Joystick.d Joystick.c -o Joystick.o
In file included from Joystick.h:53:0,
                 from Joystick.c:27:
Descriptors.h:50:10: error: conflicting types for 'CALLBACK_USB_GetDescriptor'
 uint16_t CALLBACK_USB_GetDescriptor(
          ^
In file included from ./LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.h:67:0,
                 from ./LUFA/Drivers/USB/Core/USBController.h:150,
                 from ./LUFA/Drivers/USB/Core/USBTask.h:47,
                 from ./LUFA/Drivers/USB/USB.h:386,
                 from Joystick.h:47,
                 from Joystick.c:27:
./LUFA/Drivers/USB/Core/AVR8/../Device.h:133:13: note: previous declaration of 'CALLBACK_USB_GetDescriptor' was here
    uint16_t CALLBACK_USB_GetDescriptor(const uint16_t wValue,
             ^
make: *** [Joystick.o] Error 1

**Comment by hikoae** [comment]
ive just figured out the wrong part of the code wrong for my setup, thx again for the help!
