### ISSUE TITLE
bot not working for me

### ISSUE THREAD

**Issue by Jack-Mutsers** [nnguy132/den-hoster#4]
i created and flashed the hex file to my arduino and placed my character against the den while looking at it before pluggin in the arduino. but nothing happend after i plugged it in. am i missing anything?

**Comment by nnguy132** [comment]
Hey, sorry for the late reply, which arduino are you using? And how did you go about in flashing onto the board?

**Comment by Jack-Mutsers** [comment]
I don't remember what I did back than, but by now i also found another one that I use
also I use the arduino uno R3, as for flashing i use a linux vm like i do for all hex files that i flash to the arduino
